from pathlib import Path

BASE_PATH = str(Path().absolute())
VIDEOS_PATH = f'{BASE_PATH}/videos'

LIST_VIDEOS = 'LISTAR_VIDEOS'
LIST_VIDEOS_RESPONSE = 'LISTA_DE_VIDEOS'
START_STREAMING = 'REPRODUZIR_VIDEO'
STOP_STREAMING = 'PARAR_STREAMING'
DEFAULT_RESPONSE = 'RESPONSE'
